load(
	"@platformio_rules//platformio:platformio.bzl",
	"platformio_project",
	"platformio_library"
)

platformio_library(
	visibility = ["//visibility:public"],
	name = "Test_Library",
	hdr = "test_library.h",
	src = "test_library.cc"
)
