load(
	"@platformio_rules//platformio:platformio.bzl",
	"platformio_library"
)

platformio_library(
	visibility = ["//visibility:public"],
	name = "Test-Library",
	hdr = "src/test-library.h",
	src = "src/test-library.cc"
)
