load(
	"@platformio_rules//platformio:platformio.bzl",
	"platformio_library"
)

platformio_library(
	visibility = ["//visibility:public"],
	name = "Test-Library",
	hdr = "test-library.h",
	src = "test-library.cc"
)
